### ISSUE TITLE
Push on XBMC official repository

### ISSUE THREAD

**Issue by elbowz** [sordfish/xbmc-pushbullet#1]
I would like write a client for receive pushbullet notification...and I have found your work!! :)

Why don't submit it on official repository?

**Comment by sordfish** [comment]
My girlfriend has just had our first baby so time has been limited. I have a few bugs to fix then I can submit, hope it works ok for you?

**Comment by elbowz** [comment]
Congratulations!!

Don't worry! Take care to the important things... I have do a fork, I would
see if I can add some new features to your great work:
- Add XBMC as pushbullet client. As you can send notify only to XBMC.
- Add allow/deny filter for avoid some notify to appear

Obviously, If for you is not a problem...I'll add all credit to you and
your project.

Stil Congratulations, for your baby!

Ciao,
Emanuele

**Comment by sordfish** [comment]
Thank you for your kind words.

Yes I would be very happy for you to add those features, it would make xbmc
very good!

Regards
Arran

**Comment by elbowz** [comment]
Hi Aran,

I have ended and release the first release of my work (
http://forum.xbmc.org/showthread.php?tid=204567)

Thanks again for your kindness.

Ciao,
Emanule
